# Generated by Django 4.2.7 on 2025-05-27 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='generatedimage',
            name='generation_metadata',
            field=models.JSONField(blank=True, default=dict, help_text='Additional metadata about the generation process'),
        ),
        migrations.AddField(
            model_name='generatedimage',
            name='generation_source',
            field=models.CharField(choices=[('pollinations', 'Pollinations AI'), ('huggingface', 'Hugging Face'), ('deepai', 'DeepAI'), ('mock', 'Mock Generator'), ('replicate', 'Replicate'), ('unknown', 'Unknown')], default='unknown', help_text='Which AI service generated this image', max_length=20),
        ),
    ]
