# Generated by Django 4.2.7 on 2025-06-02 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_generatedimage_generation_metadata_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='generatedimage',
            name='hashtags',
            field=models.TextField(blank=True, help_text='Generated hashtags for social sharing', null=True),
        ),
    ]
