# Generated by Django 4.2.7 on 2025-06-21 08:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_generatedimage_hashtags'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoStylePreset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField()),
                ('prompt_suffix', models.TextField(help_text='Additional prompt text to append for video')),
                ('is_active', models.BooleanField(default=True)),
                ('category', models.CharField(choices=[('animation', 'Animation'), ('cinematic', 'Cinematic'), ('abstract', 'Abstract'), ('nature', 'Nature'), ('artistic', 'Artistic')], default='animation', max_length=30)),
            ],
            options={
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='GeneratedVideo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('prompt', models.TextField(help_text='Describe the video you want to generate')),
                ('video', models.FileField(blank=True, null=True, upload_to='generated_videos/')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='video_thumbnails/')),
                ('duration', models.IntegerField(choices=[(3, '3 seconds'), (5, '5 seconds'), (10, '10 seconds'), (15, '15 seconds')], default=5)),
                ('quality', models.CharField(choices=[('draft', 'Draft (480p)'), ('standard', 'Standard (720p)'), ('high', 'High (1080p)')], default='standard', max_length=20)),
                ('fps', models.IntegerField(default=24, help_text='Frames per second')),
                ('seed', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('generation_source', models.CharField(choices=[('runway', 'Runway ML'), ('stable_video', 'Stable Video Diffusion'), ('pika_labs', 'Pika Labs'), ('zeroscope', 'Zeroscope'), ('mock', 'Mock Generator'), ('unknown', 'Unknown')], default='unknown', max_length=20)),
                ('generation_metadata', models.JSONField(blank=True, default=dict)),
                ('is_public', models.BooleanField(default=True)),
                ('hashtags', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('generation_started_at', models.DateTimeField(blank=True, null=True)),
                ('generation_completed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_videos', to=settings.AUTH_USER_MODEL)),
                ('video_style_preset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.videostylepreset')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
