# Generated by Django 4.2.7 on 2025-07-11 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_videostylepreset_generatedvideo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GeneratedVideo',
        ),
        migrations.DeleteModel(
            name='VideoStylePreset',
        ),
    ]
